# Copyright (c) 2022, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
rules:
  default: false
  custom:
    - seriesQuery: '{__name__=~"wls_webapp_config_open_sessions_current_count",pod!="",namespace!="", app="opdemo"}'
      resources:
        overrides:
          namespace:
            resource: namespace
          pod:
            resource: pod
      name:
        matches: ^(.*)
        as: "current_open_sessions_opdemo_app"
      metricsQuery: wls_webapp_config_open_sessions_current_count{<<.LabelMatchers>>,app='opdemo'}
