apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: insecure-transport
  namespace: wcv2-ns
spec:
  insecureSkipVerify: true
---
apiVersion: v1
kind: Service
metadata:
  name: wcv2-admin-clusterip
  namespace: wcv2-ns
spec:
  type: ClusterIP
  selector:
    weblogic.createdByOperator: "true"
    weblogic.domainUID: wcv2
    weblogic.serverName: wcv2wladmin0
  ports:
  - name: admin-https
    port: 7002
    targetPort: 7002
    protocol: TCP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: wcv2-admin-console
  namespace: wcv2-ns
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`admin.wcv2.telco.es`)
      kind: Rule
      services:
        - name: wcv2-admin-clusterip
          port: 7002
          scheme: https
          serversTransport: insecure-transport
  tls: {}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: wcv2-cluster-cov3
  namespace: wcv2-ns
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`cov3.wcv2.telco.es`)
      kind: Rule
      services:
        - name: wcv2-cluster-wcv2wlncov3
          port: 38700
          scheme: https
          serversTransport: insecure-transport
  tls: {}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: wcv2-cluster-cov4
  namespace: wcv2-ns
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`cov4.wcv2.telco.es`)
      kind: Rule
      services:
        - name: wcv2-cluster-wcv2wlncov4
          port: 38700
          scheme: https
          serversTransport: insecure-transport
  tls: {}